### ISSUE TITLE
morse.py complains import from __future__ is no longer at beginning of file

### ISSUE THREAD

**Issue by pwdirks** [MorseKOB/pykob-4#5]
$ python3 Clock.py 
Traceback (most recent call last):
  File "Clock.py", line 34, in <module>
    from pykob import config, kob, morse, log
  File "/Users/Patrick/Documents/Projects/Morse/MorseKOB/pykob-4/pykob/morse.py", line 31
    from __future__ import print_function  ###
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file

**Comment by pwdirks** [comment]
Resolved w. merge of pwd-5-future-import
